#ifndef TRACE_EVENT_IDS_H
#define TRACE_EVENT_IDS_H

#define traceBLOCKING_ON_QUEUE_PEEKid 1
#define traceBLOCKING_ON_QUEUE_RECEIVEid 2
#define traceBLOCKING_ON_QUEUE_SENDid 3
#define traceBLOCKING_ON_STREAM_BUFFER_RECEIVEid 4
#define traceBLOCKING_ON_STREAM_BUFFER_SENDid 5
#define traceCREATE_COUNTING_SEMAPHOREid 6
#define traceCREATE_COUNTING_SEMAPHORE_FAILEDid 7
#define traceCREATE_MUTEXid 8
#define traceCREATE_MUTEX_FAILEDid 9
#define traceEVENT_GROUP_CLEAR_BITSid 10
#define traceEVENT_GROUP_CLEAR_BITS_FROM_ISRid 11
#define traceEVENT_GROUP_CREATEid 12
#define traceEVENT_GROUP_CREATE_FAILEDid 13
#define traceEVENT_GROUP_DELETEid 14
#define traceEVENT_GROUP_SET_BITSid 15
#define traceEVENT_GROUP_SET_BITS_FROM_ISRid 16
#define traceEVENT_GROUP_SYNC_BLOCKid 17
#define traceEVENT_GROUP_WAIT_BITS_BLOCKid 18
#define traceFREEid 19
#define traceGIVE_MUTEX_RECURSIVEid 20
#define traceGIVE_MUTEX_RECURSIVE_FAILEDid 21
#define traceINCREASE_TICK_COUNTid 22
#define traceLOW_POWER_IDLE_BEGINid 23
#define traceLOW_POWER_IDLE_ENDid 24
#define traceMALLOCid 25
#define traceMOVED_TASK_TO_READY_STATEid 26
#define tracePEND_FUNC_CALLid 27
#define tracePEND_FUNC_CALL_FROM_ISRid 28
#define tracePOST_MOVED_TASK_TO_READY_STATEid 29
#define traceQUEUE_CREATEid 30
#define traceQUEUE_CREATE_FAILEDid 31
#define traceQUEUE_DELETEid 32
#define traceQUEUE_PEEKid 33
#define traceQUEUE_PEEK_FAILEDid 34
#define traceQUEUE_PEEK_FROM_ISRid 35
#define traceQUEUE_PEEK_FROM_ISR_FAILEDid 36
#define traceQUEUE_REGISTRY_ADDid 37
#define traceQUEUE_RECEIVEid 38
#define traceQUEUE_RECEIVE_FAILEDid 39
#define traceQUEUE_RECEIVE_FROM_ISRid 40
#define traceQUEUE_RECEIVE_FROM_ISR_FAILEDid 41
#define traceQUEUE_SENDid 42
#define traceQUEUE_SEND_FAILEDid 43
#define traceQUEUE_SEND_FROM_ISRid 44
#define traceQUEUE_SEND_FROM_ISR_FAILEDid 45
#define traceTAKE_MUTEX_RECURSIVEid 46
#define traceTAKE_MUTEX_RECURSIVE_FAILEDid 47
#define traceTASK_CREATEid 48
#define traceTASK_CREATE_FAILEDid 49
#define traceTASK_DELAYid 50
#define traceTASK_DELAY_UNTILid 51
#define traceTASK_DELETEid 52
#define traceTASK_INCREMENT_TICKid 53
#define traceTASK_NOTIFYid 54
#define traceTASK_NOTIFY_FROM_ISRid 55
#define traceTASK_NOTIFY_GIVE_FROM_ISRid 56
#define traceTASK_NOTIFY_TAKEid 57
#define traceTASK_NOTIFY_TAKE_BLOCKid 58
#define traceTASK_NOTIFY_WAITid 59
#define traceTASK_NOTIFY_WAIT_BLOCKid 60
#define traceTASK_PRIORITY_DISINHERITid 61
#define traceTASK_PRIORITY_INHERITid 62
#define traceTASK_PRIORITY_SETid 63
#define traceTASK_RESUMEid 64
#define traceTASK_RESUME_FROM_ISRid 65
#define traceTASK_SUSPENDid 66
#define traceTASK_SWITCHED_INid 67
#define traceTASK_SWITCHED_OUTid 68
#define traceTIMER_COMMAND_RECEIVEDid 69
#define traceTIMER_COMMAND_SENDid 70
#define traceTIMER_CREATEid 71
#define traceTIMER_CREATE_FAILEDid 72
#define traceTIMER_EXPIREDid 73
#define traceSTREAM_BUFFER_CREATEid 74
#define traceSTREAM_BUFFER_CREATE_FAILEDid 75
#define traceSTREAM_BUFFER_CREATE_STATIC_FAILEDid 76
#define traceSTREAM_BUFFER_DELETEid 77

#endif // TRACE_EVENT_IDS_H
